#!/usr/bin/env python3
"""Generate Godot SpriteFrames resources from the art pipeline's sprite sheets.

The frame counts, frame sizes, FPS and loop flags below are transcribed from
`docs/ART_SPEC.md` section 7 and the per-directory `metadata.md` files, which
are the art pipeline's source of truth. Writing the resources by hand would mean
~70 AtlasTexture blocks maintained by copy-paste; generating them means the
frame table exists once and the .tres files can be regenerated whenever
WorkBuddy replaces a sheet.

Usage (from the repository root):

    python3 tools/generate_sprite_frames.py

The generated .tres files are committed. Re-run and commit the diff if a sheet's
frame count changes.
"""

from __future__ import annotations

import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# actor -> (output path, frame width, frame height, [(anim, sheet, frames, fps, loop)])
ACTORS = {
    "player": (
        "actors/player/player_frames.tres",
        48,
        48,
        [
            ("idle", "assets/player/player_idle.png", 4, 8.0, True),
            ("run", "assets/player/player_run.png", 6, 12.0, True),
            ("jump", "assets/player/player_jump.png", 2, 10.0, False),
            ("attack", "assets/player/player_attack.png", 4, 14.0, False),
            ("hurt", "assets/player/player_hurt.png", 2, 10.0, False),
            ("death", "assets/player/player_death.png", 6, 8.0, False),
        ],
    ),
    "ghost_melee": (
        "actors/enemies/ghost_melee_frames.tres",
        48,
        48,
        [
            ("idle", "assets/enemy/ghost_melee_idle.png", 4, 8.0, True),
            ("run", "assets/enemy/ghost_melee_run.png", 6, 10.0, True),
            ("attack", "assets/enemy/ghost_melee_attack.png", 4, 12.0, False),
            ("hurt", "assets/enemy/ghost_melee_hurt.png", 2, 10.0, False),
            ("death", "assets/enemy/ghost_melee_death.png", 4, 8.0, False),
        ],
    ),
    "boss": (
        "actors/boss/boss_frames.tres",
        96,
        96,
        [
            ("idle", "assets/boss/boss_idle.png", 4, 6.0, True),
            ("run", "assets/boss/boss_run.png", 6, 8.0, True),
            ("attack", "assets/boss/boss_attack.png", 5, 10.0, False),
            ("hurt", "assets/boss/boss_hurt.png", 2, 8.0, False),
            ("death", "assets/boss/boss_death.png", 8, 6.0, False),
        ],
    ),
}

HEADER = (
    "; Generated by tools/generate_sprite_frames.py from docs/ART_SPEC.md.\n"
    "; Do not hand-edit: re-run the generator instead.\n"
)


def verify_sheet(sheet: pathlib.Path, frames: int, width: int, height: int) -> None:
    """Fail loudly if a sheet does not match the frame table."""
    try:
        from PIL import Image  # optional; skip verification when unavailable
    except ImportError:
        return
    with Image.open(sheet) as image:
        expected = (frames * width, height)
        if image.size != expected:
            raise SystemExit(
                f"{sheet.relative_to(REPO_ROOT)} is {image.size}, "
                f"expected {expected} for {frames} frames of {width}x{height}"
            )


def build(actor: str) -> str:
    output_path, frame_w, frame_h, animations = ACTORS[actor]
    ext_lines: list[str] = []
    sub_lines: list[str] = []
    animation_entries: list[str] = []

    for index, (anim, sheet, frames, fps, loop) in enumerate(animations):
        verify_sheet(REPO_ROOT / sheet, frames, frame_w, frame_h)
        ext_id = f"{index + 1}_{anim}"
        ext_lines.append(
            f'[ext_resource type="Texture2D" path="res://{sheet}" id="{ext_id}"]'
        )
        frame_refs = []
        for frame in range(frames):
            sub_id = f"AtlasTexture_{anim}_{frame}"
            sub_lines.append(
                f'[sub_resource type="AtlasTexture" id="{sub_id}"]\n'
                f'atlas = ExtResource("{ext_id}")\n'
                f"region = Rect2({frame * frame_w}, 0, {frame_w}, {frame_h})"
            )
            frame_refs.append(
                '{\n"duration": 1.0,\n'
                f'"texture": SubResource("{sub_id}")\n'
                "}"
            )
        animation_entries.append(
            "{\n"
            f'"frames": [{", ".join(frame_refs)}],\n'
            f'"loop": {"true" if loop else "false"},\n'
            f'"name": &"{anim}",\n'
            f'"speed": {fps}\n'
            "}"
        )

    load_steps = len(ext_lines) + len(sub_lines) + 1
    body = [
        HEADER + f'[gd_resource type="SpriteFrames" load_steps={load_steps} format=3]',
        "",
        "\n".join(ext_lines),
        "",
        "\n\n".join(sub_lines),
        "",
        "[resource]",
        "animations = [" + ", ".join(animation_entries) + "]",
        "",
    ]
    return "\n".join(body)


def main() -> int:
    for actor in ACTORS:
        output_path = REPO_ROOT / ACTORS[actor][0]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(build(actor), encoding="utf-8")
        print(f"wrote {output_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
